### ISSUE TITLE
Allow templates and queries to be placed in a custom directory outside of the extension

### ISSUE THREAD

**Issue by herbdool** [TechToThePeople/civisualize#117]
As far as I can tell, all the custom templates need to be inside the extension. Since we manage our extensions in a repo, this makes it a bit messy to handle.

**Comment by tttp** [comment]
I'm not sure what is the issue, but if you put the same folders in your
extension (templates / dataviz and queries) it will work fine

**Comment by herbdool** [comment]
@tttp I'm not sure what you mean, but let me be more explicit.

By extension, I mean this extension. We don't have a separate extension. I would like to be able to set an arbitrary path for this extension to find the templates and queries, much like Civi can set a `customTemplateDir` and `customPHPPathDir`. So we could set something like:

```
$civicrm_setting['Directory Preferences']['customTemplateDir'] = '/app/sites/all/civicrm_custom/civisualize';
```

And then under that could organize the files into ../civisualize/templates, ../civisualize/queries.

From the code I see that I can put them into the path set for `customTemplateDir` but it's not ideal.

**Comment by tttp** [comment]
The normal way of  doing that is to create your own placeholder extension
that just contains the needed templates and queries

Civisualize automatically look at them

Doesn't it solve your case?

**Comment by herbdool** [comment]
Thanks for responding. I'm not sure it solves it as I've never created a placeholder extension. I guess I was thinking it would be good to have something more user-friendly.

**Comment by tttp** [comment]
https://docs.civicrm.org/dev/en/latest/extensions/civix/

this is not much more complicated than changing the template, less error
prone and makes it easier to distribute and share your magic

Talking about that: if the viz you are planning to add are generic, your
contribution will be greatly appreciated

**Comment by tttp** [comment]
"writing an extension" seems a bit overselling the "civix generate:module yourmodule" ;)

my experience is that to keep stuff together organised AND avoiding very painful upgrades, putting things in "shallow" extensions is the way to go, and it comes with a lot of batteries included (eg you can easily disable/enable or move around between civi)

Every time I had to deal with a civi install using custom templates, it was stuck on an old version because some random incompatibilities. I'm not saying it would happen with civisualise, but given that it's an extra 1 min work to create a new clean extension, I'd rather not suggest folks to go the custom template way

And for the broader community, my hope is that it makes it easier to have a look at what others do and take some bits (or everything), one can hope ;)

Does it make sense?
