### ISSUE TITLE
How could we add parameters in the url to preset the screen to eg show 'last 3 months'?

### ISSUE THREAD

**Issue by petednz** [TechToThePeople/civisualize#94]
title says it all

**Comment by tttp** [comment]
hey, 

you can have custom params for the queries (using a json file instead of a sql one) 

and you have several ways of adding a parameter. The easiest one is to add it in the url, eg "civicrm/dataviz/yourviz/42

means that you will have {id} set at 42 in your template. Check out some of the custom build ones:

https://github.com/WeMoveEU/speakcivi/blob/master/templates/dataviz/WMMailing.tpl#L49

     var data = {crmSQL json="WMmailings" days=$id debug=1};
