### ISSUE TITLE
Add filter/field participant role

### ISSUE THREAD

**Issue by niels-heinemann** [TechToThePeople/civisualize#98]
Are there chances to add the participant's role to event visualization?

**Comment by tttp** [comment]
Hi,

It should be fairly trivial (and the latest version of crossfilter works great for the cases where one participant can have several roles), do you need some guidance or you are looking for someone to add that feature?

(in the later, "I could throw some money at the problem is usually a magic sentence to get the features you need ;)

**Comment by nielosz** [comment]
Hahahaha, that sounds good :D Too bad I'm suffering from both, lack of time AND lack of money :D So if you could help me out with some guidance where to start, I would be very glad. Thx in advance

**Comment by mlutfy** [comment]
Hi,

The extension has been moved to CiviCRM's Gitlab. This issue can therefore now be found at:  
https://lab.civicrm.org/extensions/civisualize/-/issues/98

Thanks!
